### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by 6594k** [badbones69/Crazy-Auctions#14]
[10:42:51 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ca' in plugin CrazyAuctions v1.2.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Paper-1104]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[spigot.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) ~[spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1393) ~[spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1198) ~[spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[spigot.jar:git-Paper-1104]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [spigot.jar:git-Paper-1104]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot.jar:git-Paper-1104]
        at me.badbones69.crazyauctions.Methods.color(Methods.java:33) ~[?:?]
        at me.badbones69.crazyauctions.Methods.makeItem(Methods.java:97) ~[?:?]
        at me.badbones69.crazyauctions.GUI.openShop(GUI.java:113) ~[?:?]
        at me.badbones69.crazyauctions.Main.onCommand(Main.java:74) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Paper-1104]
        ... 15 more

**Comment by kicjow** [comment]
Could you please (pastebin)[https://pastebin.com/] the config file.
