### ISSUE TITLE
Not compatible with EssentialsMysqlStorage

### ISSUE THREAD

**Issue by CryLegende** [badbones69/Crazy-Auctions#23]
I have this error:

> `[13:26:24] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CrazyAuctions v1.2.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199) ~[SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at com.earth2me.essentials.UserMap.getUser(UserMap.java:112) ~[?:?]
	at com.earth2me.essentials.UserMap.getUser(UserMap.java:89) ~[?:?]
	at com.earth2me.essentials.Essentials.getOfflineUser(Essentials.java:681) ~[?:?]
	at com.earth2me.essentials.Essentials.getUser(Essentials.java:667) ~[?:?]
	at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:86) ~[?:?]
	at com.earth2me.essentials.api.Economy.playerExists(Economy.java:412) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.hasAccount(Economy_Essentials.java:281) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.createPlayerAccount(Economy_Essentials.java:89) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:150) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]`

**Comment by CryLegende** [comment]
Thank you anyway... (after 2,4 years)
