### ISSUE TITLE
error when someone type /ah command

### ISSUE THREAD

**Issue by comonier** [badbones69/Crazy-Auctions#72]
[00:03:30] [Server thread/INFO]: Galactic0ls issued server command: /ah
[00:03:30] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ah' in plugin CrazyAuctions v1.2.9
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.3.jar:git-Paper-132]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.3.jar:git-Paper-132]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1837) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1645) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-132]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at me.badbones69.crazyauctions.controllers.GUI.openShop(GUI.java:57) ~[?:?]
	at me.badbones69.crazyauctions.Main.onCommand(Main.java:69) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.3.jar:git-Paper-132]
	... 17 more

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/61574121-aadaf680-aa90-11e9-931a-557aa3aa1a1c.png)
This issue starts after i have upgrade this plugins.

**Comment by comonier** [comment]
can you help me to find each one is the problem ?

**Comment by badbones69** [comment]
Seems there might be a broken item in the data file. Pastebin it and send me the file and ill look at it.

**Comment by saladfingers** [comment]
I'm also getting the exact same error after upgrade paper to 1.14.4. 

Renaming data.yml temporarily fixes the issue.

**Comment by HexedHero** [comment]
same issue https://pastebin.com/raw/y3ZUbZ3g
