### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by prozhong** [badbones69/Crazy-Auctions#8]
[17:47:12] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CrazyAuctions v1.2.1
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-916.2]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1909) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-916.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException: Nodes must be provided.
	at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:35) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68) ~[patched_1.10.2.jar:git-Paper-916.2]
	at me.badbones69.crazyauctions.SettingsManager.saveData(SettingsManager.java:83) ~[?:?]
	at me.badbones69.crazyauctions.GUI.onInvClick(GUI.java:858) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor663.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-916.2]
	... 16 more
[17:47:12] [Craft Scheduler Thread - 1111/WARN]: [CrazyAuctions] Plugin CrazyAuctions v1.2.1 generated an exception while executing task 84
java.lang.NullPointerException

**Comment by kicjow** [comment]
Very strange error. Check your CA folder and see if there is a Data.yml file in there. If not either make one and copy the default into it or delete the CA folder to let it remake.

**Comment by prozhong** [comment]
There exists Data.yml and seems no player have reported any bugs or item lost

**Comment by prozhong** [comment]
[06:50:49] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CrazyAuctions v1.2.1
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-916.2]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1909) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-916.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_121]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_121]
	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:142) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:146) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:108) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68) ~[patched_1.10.2.jar:git-Paper-916.2]
	at me.badbones69.crazyauctions.SettingsManager.saveData(SettingsManager.java:83) ~[?:?]
	at me.badbones69.crazyauctions.Methods.updateAuction(Methods.java:438) ~[?:?]
	at me.badbones69.crazyauctions.GUI.onInvClick(GUI.java:597) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor663.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-916.2]
	... 16 more

another issue : ConcurrentModificationException
They two both appears everyday

**Comment by Escartem** [comment]
Same error too : 

`org.bukkit.command.CommandException: Unhandled exception executing command 'ca' in plugin CrazyAuctions v1.2.11-RELEASE
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at me.badbones69.crazyauctions.Methods.makeItem(Methods.java:66) ~[?:?]
	at me.badbones69.crazyauctions.controllers.GUI.openViewer(GUI.java:400) ~[?:?]
	at me.badbones69.crazyauctions.Main.onCommand(Main.java:98) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.jar:git-Spigot-c8d4cef-907de3f]
	... 17 more`
