### ISSUE TITLE
clickevent 1.14.4 bug

### ISSUE THREAD

**Issue by ProDash1998** [badbones69/Crazy-Auctions#83]
[12:18:54 ERROR]: Could not pass event InventoryClickEvent to CrazyAuctions v1.2.6
java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
        at me.badbones69.crazyauctions.controllers.GUI.onInvClick(GUI.java:448) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor351.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[spigot.jar:git-Paper-206]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[spigot.jar:git-Paper-206]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Paper-206]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1023) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1016) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1082) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[spigot.jar:git-Paper-206]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[12:18:54 ERROR]: Could not pass event InventoryCloseEvent to CrazyAuctions v1.2.6
java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
        at me.badbones69.crazyauctions.controllers.GUI.onInvClose(GUI.java:435) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor350.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[spigot.jar:git-Paper-206]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[spigot.jar:git-Paper-206]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Paper-206]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[spigot.jar:git-Paper-206]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1344) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2089) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1023) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1016) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1082) ~[spigot.jar:git-Paper-206]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[spigot.jar:git-Paper-206]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by ProDash1998** [comment]
build 1.14.4 207

**Comment by badbones69** [comment]
Update to the newest CA. You are using a version that doesn't even support 1.14 lol.
