### ISSUE TITLE
cannot open expired items GUI paper 1.15.1

### ISSUE THREAD

**Issue by blackshot** [badbones69/Crazy-Auctions#90]
Error Stack trace:

`28.12 17:52:14 [Server] ERROR Could not pass event InventoryClickEvent to CrazyAuctions v1.2.11-RELEASE
28.12 17:52:14 [Server] INFO java.lang.NullPointerException: null
28.12 17:52:14 [Server] INFO at me.badbones69.crazyauctions.Methods.makeItem(Methods.java:66) ~[?:?]
28.12 17:52:14 [Server] INFO at me.badbones69.crazyauctions.controllers.GUI.openPlayersExpiredList(GUI.java:257) ~[?:?]
28.12 17:52:14 [Server] INFO at me.badbones69.crazyauctions.controllers.GUI.onInvClick(GUI.java:619) ~[?:?]
28.12 17:52:14 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor426.execute(Unknown Source) ~[?:?]
28.12 17:52:14 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2328) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1166) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-27]
28.12 17:52:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

Data.yml: https://pastebin.com/8un6qSpF
`Items:
  '3':
    Price: 200
    Seller: SirH
    Time-Till-Expire: 1577581191352
    Full-Time: 1578185991352
    StoreID: 180325
    Biddable: false
    TopBidder: None
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2227
      type: VILLAGER_SPAWN_EGG
  '4':
    Price: 10
    Seller: SirH
    Time-Till-Expire: 1577638700672
    Full-Time: 1578243500672
    StoreID: 524278
    Biddable: false
    TopBidder: None
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2227
      type: FISHING_ROD
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §bGancho de escalada
        lore:
        - §r§7§oClick derecho para lanzar
        - §r§7§o8 usos restantes
        - §r§7§oUnlimited bloques de distancia
        - §r§e
        - Encontrado en el fondo de un
        - barranco..
        enchants:
          LURE: 1
        ItemFlags:
        - HIDE_ENCHANTS
        internal: H4sIAAAAAAAAAONiYGBhEHMvSiwoyMnMS/fIz88OySjKLw/JzE1lgAJGBl4UBYyMaDqCgOxUEIeBmUEERcY3sSK0OLUYaAgHC4M4Fk3I9jAziKKocMksLknMS06FyAmiyMFMZQAA9cloEsEAAAA=
  '1':
    Price: 13
    Seller: SirH
    Time-Till-Expire: 1577724470197
    Full-Time: 1578329270197
    StoreID: 144539
    Biddable: false
    TopBidder: None
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2227
      type: TRIPWIRE_HOOK
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: ' §b§lLlave de §7§lCaja básica'
        lore:
        - §7Una llave especial
        - §7Para una caja especial.
        enchants:
          LUCK: 1
        ItemFlags:
        - HIDE_ENCHANTS
        internal: H4sIAAAAAAAAAONiYOBgEHQuSqyqBBIlqcW6YIqB1SmxODOZAQD0zToSHwAAAA==
  '5':
    Price: 13
    Seller: SirH
    Time-Till-Expire: 1577724474927
    Full-Time: 1578329274927
    StoreID: 992600
    Biddable: false
    TopBidder: None
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2227
      type: TRIPWIRE_HOOK
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: ' §b§lLlave de §7§lCaja básica'
        lore:
        - §7Una llave especial
        - §7Para una caja especial.
        enchants:
          LUCK: 1
        ItemFlags:
        - HIDE_ENCHANTS
        internal: H4sIAAAAAAAAAONiYOBgEHQuSqyqBBIlqcW6YIqB1SmxODOZAQD0zToSHwAAAA==
  '6':
    Price: 13
    Seller: SirH
    Time-Till-Expire: 1577724478001
    Full-Time: 1578329278001
    StoreID: 737287
    Biddable: false
    TopBidder: None
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2227
      type: TRIPWIRE_HOOK
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: ' §b§lLlave de §7§lCaja básica'
        lore:
        - §7Una llave especial
        - §7Para una caja especial.
        enchants:
          LUCK: 1
        ItemFlags:
        - HIDE_ENCHANTS
        internal: H4sIAAAAAAAAAONiYOBgEHQuSqyqBBIlqcW6YIqB1SmxODOZAQD0zToSHwAAAA==
  '7':
    Price: 13
    Seller: SirH
    Time-Till-Expire: 1577724484015
    Full-Time: 1578329284015
    StoreID: 335257
    Biddable: false
    TopBidder: None
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2227
      type: TRIPWIRE_HOOK
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: ' §b§lLlave de §7§lCaja básica'
        lore:
        - §7Una llave especial
        - §7Para una caja especial.
        enchants:
          LUCK: 1
        ItemFlags:
        - HIDE_ENCHANTS
        internal: H4sIAAAAAAAAAONiYOBgEHQuSqyqBBIlqcW6YIqB1SmxODOZAQD0zToSHwAAAA==
  '8':
    Price: 9
    Seller: SirH
    Time-Till-Expire: 1577726688041
    Full-Time: 1578331488041
    StoreID: 219007
    Biddable: false
    TopBidder: None
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2227
      type: NAME_TAG
  '9':
    Price: 40
    Seller: SirH
    Time-Till-Expire: 1577740673211
    Full-Time: 1578345473211
    StoreID: 62935
    Biddable: false
    TopBidder: None
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2227
      type: FISHING_ROD
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §bGancho de escalada
        lore:
        - §r§7§oClick derecho para lanzar
        - §r§7§o40 usos restantes
        - §r§7§oUnlimited bloques de distancia
        - §r§e
        - Encontrado en el fondo de un
        - barranco..
        enchants:
          LURE: 1
        ItemFlags:
        - HIDE_ENCHANTS
        internal: H4sIAAAAAAAAAONiYGBhEHMvSiwoyMnMS/fIz88OySjKLw/JzE1lgAJGBl4UBYyMaDqCgOxUEIeBmUEERcY3sSK0OLUYaIgGC4M4Fk3I9jAziKKocMksLknMS06FyAmiyMFMZQAA+cnrf8EAAAA=
OutOfTime/Cancelled:
  '1':
    Seller: SirH
    Full-Time: 1578150571599
    StoreID: 159011
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2227
      type: FISHING_ROD
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §bGancho de escalada
        lore:
        - §r§7§oClick derecho para lanzar
        - §r§7§o9 usos restantes
        - §r§7§oUnlimited bloques de distancia
        - §r§e
        - Encontrado en el fondo de un
        - barranco..
        enchants:
          LURE: 1
        ItemFlags:
        - HIDE_ENCHANTS
        internal: H4sIAAAAAAAAAONiYGBhEHMvSiwoyMnMS/fIz88OySjKLw/JzE1lgAJGBl4UBYyMaDqCgOxUEIeBmUEERcY3sSK0OLUYaAgnC4M4Fk3I9jAziKKocMksLknMS06FyAmiyMFMZQAArbC2XMEAAAA=
  '2':
    Seller: SirH
    Full-Time: 1578407328719
    StoreID: 295251
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2227
      type: GRASS_BLOCK
  '3':
    Seller: SirH
    Full-Time: 1578160211767
    StoreID: 384908
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2227
      type: DIAMOND_SWORD
`

using the default config.yml

**Comment by blackshot** [comment]
what a waste of time... the worst response time ever, nevermind i'm switching to AuctionHouse. also rating it on spigot
